name: Manual Test
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install MDQ
        uses: action-stars/install-tool-from-github-release@ece2623611b240002e0dd73a0d685505733122f6 # v0.2.4
        with:
          github_token: ${{ github.token }}
          owner: yshavit
          repository: mdq
          os_linux: ubuntu
          extract_mode_linux: zip
          extract_mode_macos: zip
          filename_format: "{name}-{os}.{ext}"
          check_command: mdq --version
          version: latest
