name: Manual Test
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install MDQ
        # uses: ./
        uses: action-stars/install-tool-from-github-release@ece2623611b240002e0dd73a0d685505733122f6
        with:
          github_token: ${{ github.token }}
          owner: yshavit
          repository: mdq
          os_linux: ubuntu
          extract_mode_linux: zip
          extract_mode_macos: zip
          filename_format: "{name}-{os}.{ext}"
          check_command: mdq --version
          version: ${{ inputs.version }}
